# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(758, 300)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Filter)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 341, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_low = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_low.setObjectName("label_low")
        self.gridLayout_2.addWidget(self.label_low, 1, 0, 1, 1)
        self.label_high = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_high.setWordWrap(False)
        self.label_high.setObjectName("label_high")
        self.gridLayout_2.addWidget(self.label_high, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label_bandpass = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_bandpass.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bandpass.setObjectName("label_bandpass")
        self.gridLayout_2.addWidget(self.label_bandpass, 0, 0, 1, 3)
        self.spinBox_high = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_high.setObjectName("spinBox_high")
        self.gridLayout_2.addWidget(self.spinBox_high, 2, 2, 1, 1)
        self.spinBox_low = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_low.setObjectName("spinBox_low")
        self.gridLayout_2.addWidget(self.spinBox_low, 2, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Filter)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 180, 651, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.horizontalLayout.addWidget(self.pushButton_Confirm)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.pushButton_Reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout.addWidget(self.pushButton_Reset)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayoutWidget = QtWidgets.QWidget(Filter)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 50, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_notch_freq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_notch_freq.setObjectName("label_notch_freq")
        self.gridLayout_3.addWidget(self.label_notch_freq, 2, 0, 1, 1)
        self.label_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_label.setMinimumSize(QtCore.QSize(0, 10))
        self.label_label.setAlignment(QtCore.Qt.AlignCenter)
        self.label_label.setObjectName("label_label")
        self.gridLayout_3.addWidget(self.label_label, 0, 0, 1, 2)
        self.spinBox_notch_freq = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_notch_freq.setObjectName("spinBox_notch_freq")
        self.gridLayout_3.addWidget(self.spinBox_notch_freq, 2, 1, 1, 1)

        self.retranslateUi(Filter)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(_translate("Filter", "Form"))
        self.label_low.setText(_translate("Filter", "低频截止频率(Hz)"))
        self.label_high.setText(_translate("Filter", "高频截止频率（Hz）"))
        self.label_bandpass.setText(_translate("Filter", "带通滤波"))
        self.pushButton_Confirm.setText(_translate("Filter", "确定"))
        self.pushButton_Cancel.setText(_translate("Filter", "取消"))
        self.pushButton_Reset.setText(_translate("Filter", "重设"))
        self.label_notch_freq.setText(_translate("Filter", "陷波频率"))
        self.label_label.setText(_translate("Filter", "陷波滤波"))
