# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_impedance.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Impedance(object):
    def setupUi(self, Impedance):
        Impedance.setObjectName("Impedance")
        Impedance.resize(942, 811)
        self.label_background = QtWidgets.QLabel(Impedance)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 781, 811))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("background.png"))
        self.label_background.setObjectName("label_background")
        self.pushButton_Confirm = QtWidgets.QPushButton(Impedance)
        self.pushButton_Confirm.setGeometry(QtCore.QRect(810, 490, 75, 23))
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.pushButton_Cancel = QtWidgets.QPushButton(Impedance)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(810, 550, 75, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.pushButton_Reset = QtWidgets.QPushButton(Impedance)
        self.pushButton_Reset.setGeometry(QtCore.QRect(810, 610, 75, 23))
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.pushButton_Fpz = QtWidgets.QPushButton(Impedance)
        self.pushButton_Fpz.setGeometry(QtCore.QRect(360, 100, 51, 51))
        self.pushButton_Fpz.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Fpz.setObjectName("pushButton_Fpz")
        self.pushButton_Fp2 = QtWidgets.QPushButton(Impedance)
        self.pushButton_Fp2.setGeometry(QtCore.QRect(450, 110, 51, 51))
        self.pushButton_Fp2.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Fp2.setObjectName("pushButton_Fp2")
        self.pushButton_Fp1 = QtWidgets.QPushButton(Impedance)
        self.pushButton_Fp1.setGeometry(QtCore.QRect(270, 110, 51, 51))
        self.pushButton_Fp1.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Fp1.setObjectName("pushButton_Fp1")
        self.pushButton_Fz = QtWidgets.QPushButton(Impedance)
        self.pushButton_Fz.setGeometry(QtCore.QRect(360, 240, 51, 51))
        self.pushButton_Fz.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Fz.setObjectName("pushButton_Fz")
        self.pushButton_Cz = QtWidgets.QPushButton(Impedance)
        self.pushButton_Cz.setGeometry(QtCore.QRect(360, 380, 51, 51))
        self.pushButton_Cz.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Cz.setObjectName("pushButton_Cz")
        self.pushButton_Pz = QtWidgets.QPushButton(Impedance)
        self.pushButton_Pz.setGeometry(QtCore.QRect(360, 530, 51, 51))
        self.pushButton_Pz.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Pz.setObjectName("pushButton_Pz")
        self.pushButton_Oz = QtWidgets.QPushButton(Impedance)
        self.pushButton_Oz.setGeometry(QtCore.QRect(360, 670, 51, 51))
        self.pushButton_Oz.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_Oz.setObjectName("pushButton_Oz")
        self.pushButton_F3 = QtWidgets.QPushButton(Impedance)
        self.pushButton_F3.setGeometry(QtCore.QRect(250, 230, 51, 51))
        self.pushButton_F3.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_F3.setObjectName("pushButton_F3")
        self.pushButton_F4 = QtWidgets.QPushButton(Impedance)
        self.pushButton_F4.setGeometry(QtCore.QRect(470, 230, 51, 51))
        self.pushButton_F4.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_F4.setObjectName("pushButton_F4")
        self.pushButton_F7 = QtWidgets.QPushButton(Impedance)
        self.pushButton_F7.setGeometry(QtCore.QRect(130, 210, 51, 51))
        self.pushButton_F7.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_F7.setObjectName("pushButton_F7")
        self.pushButton_F8 = QtWidgets.QPushButton(Impedance)
        self.pushButton_F8.setGeometry(QtCore.QRect(590, 210, 51, 51))
        self.pushButton_F8.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_F8.setObjectName("pushButton_F8")
        self.pushButton_C3 = QtWidgets.QPushButton(Impedance)
        self.pushButton_C3.setGeometry(QtCore.QRect(220, 380, 51, 51))
        self.pushButton_C3.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_C3.setObjectName("pushButton_C3")
        self.pushButton_C4 = QtWidgets.QPushButton(Impedance)
        self.pushButton_C4.setGeometry(QtCore.QRect(500, 380, 51, 51))
        self.pushButton_C4.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_C4.setObjectName("pushButton_C4")
        self.pushButton_T7 = QtWidgets.QPushButton(Impedance)
        self.pushButton_T7.setGeometry(QtCore.QRect(70, 380, 51, 51))
        self.pushButton_T7.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_T7.setObjectName("pushButton_T7")
        self.pushButton_T8 = QtWidgets.QPushButton(Impedance)
        self.pushButton_T8.setGeometry(QtCore.QRect(650, 380, 51, 51))
        self.pushButton_T8.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_T8.setObjectName("pushButton_T8")
        self.pushButton_P3 = QtWidgets.QPushButton(Impedance)
        self.pushButton_P3.setGeometry(QtCore.QRect(240, 540, 51, 51))
        self.pushButton_P3.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_P3.setObjectName("pushButton_P3")
        self.pushButton_P4 = QtWidgets.QPushButton(Impedance)
        self.pushButton_P4.setGeometry(QtCore.QRect(480, 540, 51, 51))
        self.pushButton_P4.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_P4.setObjectName("pushButton_P4")
        self.pushButton_P7 = QtWidgets.QPushButton(Impedance)
        self.pushButton_P7.setGeometry(QtCore.QRect(130, 550, 51, 51))
        self.pushButton_P7.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_P7.setObjectName("pushButton_P7")
        self.pushButton_P8 = QtWidgets.QPushButton(Impedance)
        self.pushButton_P8.setGeometry(QtCore.QRect(590, 550, 51, 51))
        self.pushButton_P8.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_P8.setObjectName("pushButton_P8")
        self.pushButton_O1 = QtWidgets.QPushButton(Impedance)
        self.pushButton_O1.setGeometry(QtCore.QRect(270, 660, 51, 51))
        self.pushButton_O1.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_O1.setObjectName("pushButton_O1")
        self.pushButton_O2 = QtWidgets.QPushButton(Impedance)
        self.pushButton_O2.setGeometry(QtCore.QRect(450, 660, 51, 51))
        self.pushButton_O2.setStyleSheet("QPushButton {\n"
"    width: 25px;\n"
"    height: 5px;\n"
"    border-radius: 25px;\n"
"    background-color: #808080;  /* 初始颜色 */\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButton_O2.setObjectName("pushButton_O2")
        self.gridLayoutWidget = QtWidgets.QWidget(Impedance)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(780, 50, 160, 113))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_Max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_Max.setObjectName("spinBox_Max")
        self.gridLayout.addWidget(self.spinBox_Max, 2, 0, 1, 1)
        self.spinBox_Min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_Min.setObjectName("spinBox_Min")
        self.gridLayout.addWidget(self.spinBox_Min, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("font: 700 9pt \"Microsoft YaHei UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)

        self.retranslateUi(Impedance)
        QtCore.QMetaObject.connectSlotsByName(Impedance)

    def retranslateUi(self, Impedance):
        _translate = QtCore.QCoreApplication.translate
        Impedance.setWindowTitle(_translate("Impedance", "Form"))
        self.pushButton_Confirm.setText(_translate("Impedance", "确定"))
        self.pushButton_Cancel.setText(_translate("Impedance", "取消"))
        self.pushButton_Reset.setText(_translate("Impedance", "重设"))
        self.pushButton_Fpz.setText(_translate("Impedance", "Fpz"))
        self.pushButton_Fp2.setText(_translate("Impedance", "Fp2"))
        self.pushButton_Fp1.setText(_translate("Impedance", "Fp1"))
        self.pushButton_Fz.setText(_translate("Impedance", "Fz"))
        self.pushButton_Cz.setText(_translate("Impedance", "Cz"))
        self.pushButton_Pz.setText(_translate("Impedance", "Pz"))
        self.pushButton_Oz.setText(_translate("Impedance", "Oz"))
        self.pushButton_F3.setText(_translate("Impedance", "F3"))
        self.pushButton_F4.setText(_translate("Impedance", "F4"))
        self.pushButton_F7.setText(_translate("Impedance", "F7"))
        self.pushButton_F8.setText(_translate("Impedance", "F8"))
        self.pushButton_C3.setText(_translate("Impedance", "C3"))
        self.pushButton_C4.setText(_translate("Impedance", "C4"))
        self.pushButton_T7.setText(_translate("Impedance", "T7"))
        self.pushButton_T8.setText(_translate("Impedance", "T8"))
        self.pushButton_P3.setText(_translate("Impedance", "P3"))
        self.pushButton_P4.setText(_translate("Impedance", "P4"))
        self.pushButton_P7.setText(_translate("Impedance", "P7"))
        self.pushButton_P8.setText(_translate("Impedance", "P8"))
        self.pushButton_O1.setText(_translate("Impedance", "O1"))
        self.pushButton_O2.setText(_translate("Impedance", "O2"))
        self.label_3.setText(_translate("Impedance", "kHz"))
        self.label.setText(_translate("Impedance", "最大阻抗值"))
        self.label_2.setText(_translate("Impedance", "最小阻抗值"))
        self.label_4.setText(_translate("Impedance", "kHz"))
        self.label_5.setText(_translate("Impedance", "阻抗区间设置"))
